### ISSUE TITLE
Downloading all notebooks as a zip gives an old and non-functioning version of notebooks

### ISSUE THREAD

**Issue by benjaminlarin** [shade-econ/sequence-jacobian#12]
Dear all, 

The notebooks that are in the zip file you get from 

> [Click here to download all notebooks as a zip](https://github.com/shade-econ/sequence-jacobian/raw/master/notebooks/notebooks.zip). 

are not the same as the ones listed separately. For example, `krusell_smith.ipynb` gives multiple warnings, and `hank.ipynb` throws an error. In case someone runs into the same issue, download the files separately. 

This could be easily fixed: The file `notebooks.zip` in the folder 

> [sequence-jacobian/notebooks/](https://github.com/shade-econ/sequence-jacobian/tree/master/notebooks)

 needs to be updated with the versions of the notebooks in that folder. 

Best, 
Ben

**Comment by bbardoczy** [comment]
Thanks for pointing this out! I finally fixed it.
