### ISSUE TITLE
Endogenous labor model / NUMBA update

### ISSUE THREAD

**Issue by carloseduardosg** [shade-econ/sequence-jacobian#18]
Hi, already bugged Adrien and Bence with this, but could not resolve the issue...I managed to downgrade my numba package from 0.54.2 to 0.51.0 and still my code crashes when running the HANK 1 asset endogenous labor model. Any clues?

**Comment by lukas-hack** [comment]
If this is still about the steady-state not being found due to Numba updates look here: https://github.com/shade-econ/sequence-jacobian/issues/10

I posted a simple way of adjusting the code to make it work.
