### ISSUE TITLE
endogenous grid method problem

### ISSUE THREAD

**Issue by 121180875** [shade-econ/sequence-jacobian#24]
I am reading your sample code, and I am confused about your endogenous grid method for solving the Bellman equation concerning household optimization problems. It seems different from the endogenous grid method described in the articles I previously read. Could you please tell me what the algorithm process of your endogenous grid method is?

**Comment by bbardoczy** [comment]
Hello! [This notebook](https://github.com/shade-econ/nber-workshop-2023/blob/main/Lectures/Lecture%201%2C%20Standard%20Incomplete%20Markets%20Steady%20State.ipynb) explains all the details.
