### ISSUE TITLE
pip install sequence-jacobian does not work for me

### ISSUE THREAD

**Issue by azinoma** [shade-econ/sequence-jacobian#6]
Dear all,
thank you for making your amazing codes publicly available.
I learned so much already, not only from your paper, but especially also from your code =) (so far from the old version).
Just wanted to say that, for me,
`pip install sequence-jacobian`
keeps returning
`ERROR: Could not find a version that satisfies the requirement sequence-jacobian`
`ERROR: No matching distribution found for sequence-jacobian`.
Any recommendation on what to do would be appreciated.
Many greetings and thanks again,
Marlon

**Comment by bbardoczy** [comment]
Hi Marlon,
Yes, I'm afraid I got ahead of myself with that. We decided to do a bit more polishing and `sequence_jacobian` is not on PyPI yet. It's a matter of 1-2 days. In the meantime, please install from git via: 
```
pip install git+https://github.com/shade-econ/sequence-jacobian@master
``` 
Best,
Bence
